version: '3.8'

services:
    misland-api-registry:
      image: registry:2.7
      ports:
        - "5000:5000"
      deploy:
        replicas: 1
        restart_policy:
          condition: any
      volumes:
        - registry-data::/var/lib/registry
      networks:
        - misland-network

volumes:
    registry-data:
        external: true
