version: '3.8'

services:
  app:
    extends:
      file: base.yml
      service: base
    ports:
      - "3000:3000"
    env_file:
      - prod.env
    command: start
    volumes:
      - ./misland_api:/opt/misland-api/misland_api
      - ./migrations:/opt/misland-api/migrations
      - ./data/scripts:/data/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - misland-api-database
      - misland-api-redis
    networks:
      - misland-network
    environment:
      - WAIT_HOSTS=misland-api-database:5432
      - WAIT_TIMEOUT=120
      - PORT=3000

  worker:
    extends:
      file: base.yml
      service: base
    env_file:
      - prod.env
    command: worker
    volumes:
      - ./misland_api:/opt/misland-api/misland_api
      - ./migrations:/opt/misland-api/migrations
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/scripts:/data/scripts
    depends_on:
      - misland-api-database
      - misland-api-redis
    networks:
      - misland-network
    environment:
      - WAIT_HOSTS=misland-api-database:5432
      - WAIT_TIMEOUT=120
      - PORT=3000

  misland-api-database:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - prod.env
    ports:
      - "5432:5432"
    networks:
      - misland-network

  misland-api-registry:
    image: registry:2.7
    ports:
      - "5100:5000"
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - misland-network

  misland-api-redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - misland-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - misland-network

volumes:
  postgres-data:
  registry-data:

networks:
  misland-network:
