version: '2'

services:
    develop:
      extends:
        file: base-develop.yml
        service: base
      container_name: misland-api-develop
      ports:
        - "3000:3000"
      env_file:
        - develop.env
      command: develop
      volumes:
        - ./misland_api:/opt/misland-api-api/misland_api
        - ./migrations:/opt/misland-api/migrations
        - /var/run/docker.sock:/tmp/docker.sock
        - ./data/scripts:/data/scripts
      restart: always
      links:
        - misland-api-database
        - registry
        - redis
      environment:
        - WAIT_HOSTS=misland-api-database:5432
        - WAIT_TIMEOUT=120
    worker:
      extends:
        file: base.yml
        service: base
      container_name: misland-api-worker-develop
      env_file:
        - develop.env
      command: worker
      volumes:
        - ./misland_api:/opt/misland-api/misland_api
        - ./migrations:/opt/misland-api/migrations
        - /var/run/docker.sock:/tmp/docker.sock
        - ./data/scripts:/data/scripts
      restart: always
      links:
        - misland-api-database
        - registry
        - redis
      environment:
        - WAIT_HOSTS=misland-api-database:5432
        - WAIT_TIMEOUT=120

    misland-api-database:
      image: postgres:9.6
      container_name: misland-api-database
      env_file:
        - prod.env
      volumes:
        - postgres-data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      restart: always

    registry:
      image: registry:2.6.1
      container_name: misland-api-registry
      env_file:
        - develop.env
      ports:
        - 5100:5000
      restart: always          
      # volumes:
      #   - /var/lib/registry:/var/lib/registry

    redis:
        image: redis
        container_name: misland-api-redis
        env_file:
          - develop.env
        ports:
          - 6379
        restart: always

volumes:
    postgres-data:
